name = "homepage"
pages_build_output_dir = "./dist"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "dedb9086175244e79a9a73bf3e256281"

[vars]
ADMIN_PASSWORD="dd2026homepage"
